0.4.11

diff --git a/docker-compose-magento b/docker-compose-magento
--- a/docker-compose-magento
+++ b/docker-compose-magento
@@ -21,7 +21,7 @@ if [[ -z $COMPOSE_PROJECT_APPDIR ]]; then
   if [ -z "$(ls $PWD)" ]; then
     export COMPOSE_PROJECT_APPDIR="$PWD"
   else
-    echo "Application root folder not found, and current directory is not empty, terminating..."
+    >&2 echo "Application root folder not found, and current directory is not empty, terminating..."
     exit 1
   fi
 fi
@@ -84,23 +84,23 @@ else
 fi
 
 if [[ -f "$COMPOSE_PROJECT_APPDIR/.docker-compose.user.yml" ]]; then
-  echo "==> Additional docker compose config will be used: $COMPOSE_PROJECT_APPDIR/.docker-compose.user.yml"
+  >&2 echo "==> Additional docker compose config will be used: $COMPOSE_PROJECT_APPDIR/.docker-compose.user.yml"
   DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f $COMPOSE_PROJECT_APPDIR/.docker-compose.user.yml"
 fi
 
 if [[ -f "$COMPOSE_PROJECT_APPDIR/.php-version" ]] && [[ -z $COMPOSE_PROJECT_PHP_VERSION ]]; then
   export COMPOSE_PROJECT_PHP_VERSION=$(cat $COMPOSE_PROJECT_APPDIR/.php-version | head -n1)
-  echo "==> Found .php-version with following version: $COMPOSE_PROJECT_PHP_VERSION"
+  >&2 echo "==> Found .php-version with following version: $COMPOSE_PROJECT_PHP_VERSION"
 fi
 
 if [[ -f "$COMPOSE_PROJECT_APPDIR/.phprc" ]] && [[ -z $COMPOSE_PROJECT_PHP_VERSION ]]; then
   export COMPOSE_PROJECT_PHP_VERSION=$(cat $COMPOSE_PROJECT_APPDIR/.phprc | head -n1)
-  echo "==> Found .phprc with following version: $COMPOSE_PROJECT_PHP_VERSION"
+  >&2 echo "==> Found .phprc with following version: $COMPOSE_PROJECT_PHP_VERSION"
 fi
 
 if [[ -f "$COMPOSE_PROJECT_APPDIR/.nvmrc" ]] && [[ -z $COMPOSE_PROJECT_NODE_VERSION ]]; then
   export COMPOSE_PROJECT_NODE_VERSION=$(cat $COMPOSE_PROJECT_APPDIR/.nvmrc | head -n1)
-  echo "==> Found .nvmrc with following version: $COMPOSE_PROJECT_NODE_VERSION"
+  >&2 echo "==> Found .nvmrc with following version: $COMPOSE_PROJECT_NODE_VERSION"
 fi
 
 if [[ "$OSTYPE" == "darwin"* ]] && [[ $1 != 'install' ]]; then
@@ -129,7 +129,7 @@ if [[ $COMPOSE_PROJECT_MODE == "mutagen" ]] && [[ -f "${COMPOSE_PROJECT_CONFIG_D
       mutagen sync terminate "${MUTAGEN_SESSION_NAME}"
     fi
     WAIT_SYNC=""
-  elif echo $1 | grep -v -i '^build\|pull' > /dev/null; then
+  elif echo $1 | grep -v -i '^\(build\|pull\)' > /dev/null; then
     if [[ "0" -eq $(${DOCKER_COMPOSE_BIN} ps -q mutagen  2> /dev/null | wc -l > /dev/null) ]]; then
       ${DOCKER_COMPOSE_BIN} up -d mutagen
     fi
@@ -185,7 +185,7 @@ fi
 
 if echo $1 | grep -i 'import' | grep -i 'db\|database' > /dev/null; then
   if [[ -z $2 ]]; then
-    echo "Data file was not provided"
+    >&2 echo "Data file was not provided"
     exit 1
   fi
   if [[ -r $2 ]]; then
@@ -195,7 +195,7 @@ if echo $1 | grep -i 'import' | grep -i 'db\|database' > /dev/null; then
   fi
 
   if [[ -z $DB_DUMP ]] || [[ ! -r $DB_DUMP ]]; then
-    echo "Data file '$2' does not readable"
+    >&2 echo "Data file '$2' does not readable"
     exit 1
   fi
 
@@ -207,7 +207,7 @@ if echo $1 | grep -i 'import' | grep -i 'db\|database' > /dev/null; then
   fi
   DB_IMPORT_CMD="cat /${DB_DUMP_BASENAME} | ${DB_IMPORT_CMD}"
 
-  echo "Starting import of the database dump..."
+  >&2 echo "Starting import of the database dump..."
   exec ${DOCKER_COMPOSE_RUN_CMD} -v "${DB_DUMP}:/${DB_DUMP_BASENAME}" database-cli bash -c "$DB_IMPORT_CMD"
 fi
 
@@ -217,37 +217,9 @@ if echo $1 | grep -i 'export\|dump' | grep -i 'db\|database' > /dev/null; then
   touch "${DB_DUMP}"
   DB_EXPORT_CMD="MYSQL_PWD=\$DATABASE_PASSWORD mysqldump --no-tablespaces --column-statistics=0 --set-gtid-purged=OFF --quick --max-allowed-packet=16M --disable-keys --hex-blob --no-autocommit --insert-ignore --skip-lock-tables --single-transaction -h\$DATABASE_HOST -P\$DATABASE_PORT -u\$DATABASE_USER \$DATABASE_NAME | sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/DEFINER=CURRENT_USER \*/'"
 
-  echo "/* Starting export of the database... */"
-  echo "/* Dumping database to: $DB_DUMP */"
+  >&2 echo "/* Starting export of the database... */"
+  >&2 echo "/* Dumping database to: $DB_DUMP */"
   exec ${DOCKER_COMPOSE_RUN_CMD} -v "${DB_DUMP}:/${DB_DUMP_BASENAME}" database-cli bash -c "$DB_EXPORT_CMD | gzip > /${DB_DUMP_BASENAME}"
-fi
-
-if echo $1 | grep -i 'database' | grep -i 'setup\|config\|configure' > /dev/null; then
-  exec ${DOCKER_COMPOSE_RUN_CMD} cli bash <<COMMANDS
-set -x
-set -e
-bin/magento setup:config:set --quiet --db-host \$DATABASE_HOST --db-user \$DATABASE_USER --db-password \$DATABASE_PASSWORD --db-name \$DATABASE_NAME
-bin/magento app:config:import --quiet
-COMMANDS
-fi
-
-if echo $1 | grep -i 'redis' | grep -i 'setup\|config\|configure' > /dev/null; then
-  exec ${DOCKER_COMPOSE_RUN_CMD} cli bash <<COMMANDS
-set -x
-set -e
-bin/magento setup:config:set --quiet --cache-backend redis --cache-backend-redis-server redis --cache-backend-redis-port 6379 --cache-backend-redis-db 0
-bin/magento setup:config:set --quiet --session-save redis --session-save-redis-host redissession --session-save-redis-port 6379 --session-save-redis-db 0
-bin/magento app:config:import --quiet
-COMMANDS
-fi
-
-if echo $1 | grep -i 'es\|elastic' | grep -i 'setup\|config\|configure' > /dev/null; then
-  exec ${DOCKER_COMPOSE_RUN_CMD} cli bash <<COMMANDS
-set -x
-set -e
-bin/magento config:set catalog/search/elasticsearch7_server_hostname elasticsearch
-bin/magento config:set catalog/search/elasticsearch7_server_port 9200
-COMMANDS
 fi
 
 if echo $1 | grep -i '^mysql' > /dev/null; then
@@ -260,7 +232,7 @@ if echo $1 | grep -i '^mysql' > /dev/null; then
   exec ${DOCKER_COMPOSE_RUN_CMD} database-cli bash -c "$MYSQL_CMD"
 fi
 
-if echo $1 | grep -i '^composer\|bin/\|npm\|php\|node\|yarn\|bash' > /dev/null; then
+if echo $1 | grep -i '^\(composer\|bin/\|npm\|php\|node\|yarn\|bash\|n98-magerun\)' > /dev/null; then
   for i in "$@"; do
       i="${i//\\/\\\\}"
       i="${i//$/\\$}"
