0.4.13

diff --git a/docker-compose-magento b/docker-compose-magento
--- a/docker-compose-magento
+++ b/docker-compose-magento
@@ -51,7 +51,9 @@ if [[ -f "$COMPOSE_PROJECT_APPDIR/.env" ]]; then
 fi
 
 if [[ -z $COMPOSE_PROJECT_COMPOSER_AUTH ]] && [[ -z $COMPOSER_AUTH ]] && which composer > /dev/null 2>&1; then
-  COMPOSER_AUTH_JSON=$(composer config --no-interaction --global home 2>/dev/null)/auth.json
+  COMPOSER_AUTH_JSON=$(composer config --no-interaction --global home 2>/dev/null)/auth.json || {
+    >&2 echo "==> Can't load composer auth.json"
+  }
   if [[ -f "${COMPOSER_AUTH_JSON}" ]]; then
     COMPOSE_PROJECT_COMPOSER_AUTH=$(cat "${COMPOSER_AUTH_JSON}")
   fi
